name: ZTC Kernel Build mksu
permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build-kernel-mkernelsu-susfs:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: Free disk space (light)
        run: |
          echo "Freeing disk space..."
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android
          sudo docker image prune -a -f
          sudo apt-get clean
          df -h

      - name: 设定 CONFIG 环境变量
        run: |
          CONFIG="android12-5.10-lts"
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
          echo "CONFIG set to: $CONFIG"

      - name: 安装依赖
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y ccache python3 git curl build-essential libssl-dev bison flex libelf-dev dwarves jq zip

      - name: 配置 ccache
        run: |
          mkdir -p ~/.cache/bazel
          ccache --version
          ccache --max-size=2G
          ccache --set-config=compression=true
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

      - name: 配置 Git
        run: |
          git config --global user.name "zzh20188"
          git config --global user.email "BuildGkiKernel@gmail.com"
      
      - name: 安装 repo 工具
        run: |
          mkdir -p ./git-repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
          chmod a+rx ./git-repo/repo
          echo "REPO=$GITHUB_WORKSPACE/./git-repo/repo" >> $GITHUB_ENV

      - name: 克隆 AnyKernel3 和依赖
        run: |
          ANYKERNEL_BRANCH="gki-2.0"
          SUSFS_BRANCH="gki-android12-5.10"
          git clone https://github.com/WildPlusKernel/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH"
          git clone https://github.com/WildPlusKernel/kernel_patches.git
          git clone https://github.com/zzh20188/GKI_KernelSU_SUSFS.git zzh_patch

      - name: 初始化并同步内核源
        run: |
          mkdir -p "$CONFIG"
          cd "$CONFIG"
          FORMATTED_BRANCH="android12-5.10-lts"
          $REPO init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-${FORMATTED_BRANCH}
          $REPO sync -c -j$(nproc --all)
          rm -rf common
          git clone https://github.com/ztc1997/android_gki_kernel_5.10_common.git --recurse-submodules --depth=1 common
          curl -LSs "https://github.com/zzh20188/ZTC-Kenel-Build/releases/download/clang/clang-r563880.tar.gz" -o clang-r563880.tar.gz
          mkdir -p prebuilts-master/clang/host/linux-x86/clang-r563880
          tar -xzvf clang-r563880.tar.gz -C prebuilts-master/clang/host/linux-x86/clang-r563880
          cd common
          sed -i 's|^CLANG_PREBUILT_BIN=.*|CLANG_PREBUILT_BIN=prebuilts-master/clang/host/linux-x86/clang-r563880/bin|' build.config.common

      - name: 添加 KernelSU (MKernelSU)
        run: |
          cd "$CONFIG/common"
          echo "Cloning MKernelSU..."
          git clone https://github.com/5ec1cff/KernelSU.git
          echo "Integrating MKernelSU into kernel..."
          echo "obj-y += KernelSU/" >> security/Makefile
          echo "CONFIG_KSU=y" >> arch/arm64/configs/gki_defconfig

      - name: 为 KernelSU 安装 SUSFS 补丁
        run: |
          cd "$CONFIG"
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch ./common/
          cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          cd ./common
          patch -p1 --fuzz=3 < 50_add_susfs_in_gki-android12-5.10.patch || true

      - name: 添加 SUSFS 配置
        run: |
          cd "$CONFIG/common"
          echo "Adding SUSFS configuration..."
          cat >> arch/arm64/configs/gki_defconfig <<'EOF'
          CONFIG_KPM=y
          CONFIG_KSU_MANUAL_HOOK=y
          CONFIG_KSU_SUSFS=y
          CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_PATH=y
          CONFIG_KSU_SUSFS_SUS_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_TRY_UMOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
          CONFIG_KSU_SUSFS_ENABLE_LOG=y
          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
          EOF

      - name: 构建内核
        run: |
          cd "$CONFIG"
          LTO=thin KCFLAGS="-O3" BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh CC=clang

      - name: 调试输出
        run: |
          echo "Checking output..."
          find $CONFIG/common/out -type f -name "Image*" | head -n 20

      - name: 复制构建产物
        run: |
          mkdir bootimgs
          cp ./$CONFIG/common/out/android12-5.10-lts/dist/Image ./bootimgs/ || true
          cp ./$CONFIG/common/out/android12-5.10-lts/dist/Image.lz4 ./bootimgs/ || true
          cp ./$CONFIG/common/out/android12-5.10-lts/dist/Image . || true
          cp ./$CONFIG/common/out/android12-5.10-lts/dist/Image.lz4 . || true
          gzip -n -k -f -9 ./Image || true

      - name: 复制 Image 至 AnyKernel3
        run: |
          cp ./Image ./AnyKernel3/Image || true
          cp ./Image.lz4 ./AnyKernel3/Image.lz4 || true

      - name: 打包 ZIP
        run: |
          cd ./AnyKernel3
          zip -r ../ZTC-AnyKernel3.zip ./*
          echo "ZIP created: ZTC-AnyKernel3.zip"

      - name: 上传编译结果
        uses: actions/upload-artifact@v4
        with:
          name: ZTC-AnyKernel3
          path: ./ZTC-AnyKernel3.zip
